In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [3]:
a

In [4]:
type(a)

numpy.ndarray

In [5]:
a[2]

3

In [6]:
a + 10

array([11, 12, 13, 14, 15])

In [7]:
a / 0.5

array([ 2.,  4.,  6.,  8., 10.])

In [8]:
b = 10 * a

In [9]:
a * b

array([ 10,  40,  90, 160, 250])

In [10]:
a + b

array([11, 22, 33, 44, 55])

In [11]:
a * b

array([ 10,  40,  90, 160, 250])

In [12]:
a / b

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [27]:
b.sum()

150

Jupyter inaczej niż w Python - podejście matematyczne

In [13]:
np.arange(3, 10, 0.25)

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 ,
       5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25,
       8.5 , 8.75, 9.  , 9.25, 9.5 , 9.75])

In [14]:
np.zeros(6), np.ones(6)

(array([0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1.]))

In [15]:
c = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])

In [16]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [17]:
c[0: 2]

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
c[0, 2]

3

In [20]:
c

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [35]:
c + 100

array([[101, 102, 103],
       [103, 104, 105],
       [105, 106, 107]])

In [36]:
c * np.array([[0, 1, 0], [1, 1000, 1], [0, 1, 0]])

array([[   0,    2,    0],
       [   3, 4000,    5],
       [   0,    6,    0]])

In [21]:
np.arange(100).shape

(100,)

In [24]:
d = np.arange(100).reshape(10, 10)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
d.sum()

4950

In [31]:
d.sum(axis=0, keepdims=True)

array([[450, 460, 470, 480, 490, 500, 510, 520, 530, 540]])

In [33]:
d.sum(axis=1, keepdims=True)

array([[ 45],
       [145],
       [245],
       [345],
       [445],
       [545],
       [645],
       [745],
       [845],
       [945]])

In [39]:
np.arange(5) * np.arange(5).reshape(5, 1)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [41]:
np.arange(5) * np.array([0, 0, 1, 0, 0]).reshape(5, 1)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])